
spring:
  threads:
    virtual:
      enabled: true
#  mail:
#    host: smtp.gmail.com
#    port: 584
#    test-connection: true
#    protocol: smtp
  hateoas:
    use-hal-as-default-json-media-type: true
  profiles:
    active: dev
server:
  port: 9090
  http2:
    enabled: true
springdoc:
  swagger-ui:
    display-request-duration: true
    deep-linking: true
    try-it-out-enabled: true