services:
    postgres:
      image: 'postgres:latest'
      environment:
        - 'POSTGRES_DB=hanjam_auth_server'
        - 'POSTGRES_PASSWORD=secret'
        - 'POSTGRES_USER=postgres'
      ports:
        - '5432:5432'